config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: "home#index"

  resources :users, except: [:new, :create, :destroy]

  resources :paths do
    resources :comments
    resources :votes
    resources :steps, except: [:show]
  end

  resources :assets, except: [:new] do
    resources :comments
    resources :votes
  end

  resources :tags, only: [:create, :new]
end

app/models/path.rb
class Path < ActiveRecord::Base
  default_scope { order(:created_at => :asc) }

  belongs_to :user
  has_and_belongs_to_many :tags
  has_many :steps, :dependent => :destroy
  has_many :comments, as: :commentable, :dependent => :destroy
  has_many :votes, as: :voteable, :dependent => :destroy

  validates :title, :description, :user_id, presence: true
end

app/models/paths.rb
class Path < ActiveRecord::Base
  belongs_to :user
  has_many :tags
  has_many :takeaways
  has_many :resources, through: :takeaways
  has_many :comments, as: :commentable
  has_many :votes, as: :voteable

  validates :title, :description, :user_id, presence: true
end

app/controllers/paths_controller.rb
class PathsController < ApplicationController
  include ApplicationHelper
  before_action :redirect_to_sign_up, only: [:new, :create, :update, :edit, :destroy]
  before_action :check_owner, only: [:edit, :update, :destroy]

  def index
    @paths = Path.all
  end

  def new
    @path = Path.new
  end

  def create
    tags_to_add = params[:path][:tags].nil? ? [] : remove_tags_from_params![:tags].split(/,\s*/)
    path = Path.new(path_params.merge(user_id: current_user.id))
    if path.save
      tags_to_add.each do |tag|
        path.tags <<  if Tag.find_by_name(tag).nil?
                        Tag.create(name: tag)
                      else
                        Tag.find_by_name(tag)
                      end
      end
      redirect_to path_path(path)
    else
      render :new
    end
  end

  def edit
    @path = Path.find(params[:id])
  end

  def update
    path = Path.find(params[:id])
    path.update(path_params)
    if path.save
      redirect_to paths_path
    else
      render :edit
    end
  end

  def show
    @path = Path.find(params[:id])
    @votes_count = vote_count(params[:id], 'Path')
    @tags = @path.tags
  end

  def destroy
    Path.find(params[:id]).destroy
    redirect_to paths_path
  end

private
  def path_params
    params.require(:path).permit(:title, :description, :user_id)
  end

  def tags_params
    params.require(:path).permit(:tags)
  end

  def check_owner
    unless Path.find(params[:id]).user_id == current_user.id
      flash[:alert] = "You cannot edit or destroy a path you do not own!"
      redirect_to paths_path and return
    end
  end

  def remove_tags_from_params!
    tags_params.extract!(:tags)
  end
end

app/views/paths/edit.html.erb
<div class="login">
  <h2 class="path-header">Edit Path</h2>
  <%= form_for(@path) do |f| %>
   <ul>
    <%= f.label :title %><br>
    <%= f.text_field :title, :class =>"title-field"  %>
  </ul>
   <ul>
    <%= f.label :description %><br>
    <%= f.text_field :description, :class =>"description-field"  %>
  </ul>
   <ul>
    <%= f.submit :class => "styled-button"%>
  </ul>
  <% end %>
</div>

app/views/paths/index.html.erb
<% if @paths.nil? %>
  <h1>There are currently no paths to display!</h1>
<% else %>

  <h2 id="pick-a-path">Choose a Path to Explore</h2>
  <% if current_user %>
    <button class="styled-button new-path-button" id="path-index-button"><%= link_to "Create New Path", new_path_path %></button>
  <% else %>
      <p class="notice">You must sign in to create a path</p>
  <% end %>
  <% @paths.each do |path| %>
      <ul class="path-index-list">
        <div class="path-index-item">
          <li class="path-title"><%= link_to path.title, path_path(path) %></li>
          <li class="path-author">Created by: <%= path.user.first_name %></li>
          <li class="path-description"><%= path.description %></li>
          <% if current_user && current_user.id == path.user_id %>
            <li><button class="styled-button"><%= link_to "Edit Path", edit_path_path(path) %></button></li>
          <% end %>
        </div>
      </ul>
  <% end %>
<% end %>

app/views/paths/new.html.erb
<div id="create-new-path">
  <%= form_for(@path) do |f| %>
  <ul>
    <%= f.label :title, :class=>"input-label" %><br>
    <%= f.text_area :title, :class=>"title-field" %>
  </ul>
  <ul>
    <%= f.label :description, :class=>"input-label" %><br>
    <%= f.text_area :description, :class=>"description-field ", :cols => 10, :rows => 10 %>
  </ul>
  <ul>
    <%= f.label :please_enter_tags_separated_by_commas, :class=>"input-label" %><br>
    <input type="text" name="path[tags]" id="tags-for-path" class="title-field">
  </ul>
  <ul>
    <%= f.submit "Create Path", :class=>"styled-button create-path-button" %>
  </ul>
  <% end %>
</div>

app/views/paths/show.html.erb
<div class="path-container">
  <h1 class="path-header"><%= @path.title %></h1>
  <div id="path-tags" class:"col-md-10">
    <% @tags.each do |tag| %>
      <p class="tag"><%= tag.name %></p>
    <% end %>
  </div>
  <h3 id="big-path-description"class="show-path-description"><%= @path.description %></h3>
  <p>
    <span id="creator">Created by: <%= @path.user.first_name %></span> <span id="vote-count">Votes: <%= @votes_count %></span>
    <% if user_signed_in? %>
      <button class="vote styled-button" data-vote-state=true data-voteable-id=<%= @path.id %> data-voteable-type="Path" ><span class="glyphicon glyphicon-arrow-up"></span>Upvote!</button>
      <button class="vote styled-button" data-vote-state=false data-voteable-id=<%= @path.id %> data-voteable-type="Path" ><span class="glyphicon glyphicon-arrow-down"></span> Downvote!</button>
    <% end %>
    <% if check_user_id(@path) %>
      <button class="styled-button"><%= link_to "Delete Path", path_path(@path), :method => :delete %></button>
      <button class="styled-button"><%= link_to "Edit Path Details", edit_path_path(@path) %></button>
      <button class="styled-button"><%= link_to "New Step", new_path_step_path(@path) %></button>
      <%= render 'tags/new', layout: false %>
    <% end %>
  </p>

  <br>
  <div class="steps-list">
    <% @path.steps.order(:position).each do |step| %>
      <div class="step-div">
        <p>
          <span class="step-body">
            <span class="step-position"><%= step.position %></span>
            <span class="<%= step.asset.category %>" title="Type: <%= step.asset.category %>"></span>
            <br>
            <%= step.body %>
          </span>
        </p>
        <p class="asset-link">
          <a href="<%= step.asset.url %>" target="_blank"><%= step.asset.title %>
            <br>
            <img class="url-preview" src="http://api.pagepeeker.com/v2/thumbs.php?size=m&url=<%= step.asset.url %>" alt="<%= step.asset.url %>" />
          </a>
        </p>
        <p class="asset-description"><%= step.asset.description %></p>
        <% if check_user_id(step.path) %>
          <button class="styled-button"><%= link_to "Delete Step", polymorphic_path([@path, step]), :method => :delete %></button>
          <button class="styled-button"><%= link_to "Edit Step", polymorphic_path([:edit, @path, step]) %></button>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="row col-md-10">
    <h3>Comments</h3>
    <hr>
     <% if user_signed_in? %>
      <button class="styled-button" id="new-comment-button"><%= link_to "New Comment", polymorphic_path([@path, Comment]) %></button>
     <% end %>
    <% @path.comments.each do |comment|%>
      <p><span class="glyphicon glyphicon-comment"></span>
           <%= link_to "Edit", polymorphic_path([:edit, @path, comment]) %> <%= link_to "Delete", polymorphic_path([@path, comment]), method: :delete %></p>
      <p class="path-comment"><%= comment.body %></p>
        <%= comment.created_at.strftime('%a %d %b %Y %I:%M %p') %> By: <%= comment.user.first_name %> <%= comment.user.last_name %><br>
      <br>
    <% end %>
  </div>
</div>