config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: "home#index"

  resources :users, except: [:new, :create, :destroy]

  resources :paths do
    resources :comments
    resources :votes
    resources :steps, except: [:show]
  end

  resources :assets, except: [:new] do
    resources :comments
    resources :votes
  end

  resources :tags, only: [:create, :new]
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :comments
  has_many :paths
  has_many :assets
  has_many :votes

  validates :email, :first_name, :last_name, presence: true
  validates :email, uniqueness: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:linkedin]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      name = auth.info.name.split(" ")
      user.first_name = name[0]
      user.last_name = name[1] 
    end
  end

 def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.data"] && session["devise.data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end  
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def linkedin
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication 
      set_flash_message(:notice, :success, :kind => "linkedin") if is_navigational_format?
    else
      session["devise.linkedin_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # ==============================================================
  # ===== Do I need to include before actions for users??? =======
  # ==============================================================
  include ApplicationHelper
  before_action :redirect_to_sign_up, only: [:new, :create, :update, :edit, :destroy]
  before_action :check_owner, only: [:edit, :update, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new  # don't know if this is necessary but wanted to include it for good measure
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    user.update(user_params)
    if user.save
      redirect_to users_path
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
  end

private

  def user_params
    params.require(:path).permit(:description)
  end
end

app/views/users/show.html.erb
<div class="user-container col-md-12">
  <h1 class="path-header">Welcome <%= @user.first_name.capitalize %> <%= @user.last_name.capitalize %></h1>
    <% if @user.paths.nil? %>
      <h1>There are currently no paths to display!</h1>
    <% else %>
      <% if current_user %>
        <button class="styled-button pad-edge new-path-button"><%= link_to "Create New Path", new_path_path %></button>
      <% else %>
        <p class="notice">You must sign in to create a path</p>
      <% end %>
      <h2 class="path-header">Your Paths</h2>
      <div class="user-path-container col-md-9">
        <% @user.paths.each do |path| %>
          <ul class="col-md-4">
            <div class="path-item">
              <li class="path-title"><%= link_to path.title, path_path(path) %></li>
              <li class="path-author">Created by: <%= path.user.first_name %></li>
              <li class="path-description"><%= path.description %></li>
              <% if current_user && current_user.id == path.user_id %>
              <li><button class="styled-button"><%= link_to "Edit Path", edit_path_path(path) %></button></li>
              <% end %>
            </div>
          </ul>
        <% end %>
    <% end %>
  </div>

  <div class="user-assets">
    <h2 class="path-header">Your Links</h2>
    <div id="assets-partial">
      <%= render 'assets/new', layout: false, locals: {asset: @new_asset} %>
    </div>
    <button class="styled-button create-assets-button">Create Link</button>
    <% if @user.assets.empty? %>
      <h3>There are currently no links to display!</h3>
    <% else %>
      <div id="asset-list">
        <% @user.assets.each do |asset| %>
          <div class="asset user-asset-list">
            <h3><%= asset.title %></h3>
            <p>Description: <%= asset.description %></p>
              <button class="styled-button"><%= link_to "Details", asset_path(asset) %></button>
              <button class="styled-button"><a href="<%= asset.url %>">View Link</a></button>
            <p>Description: <%= asset.description %></p>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>