config/routes.rb
Rails.application.routes.draw do
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: "home#index"

  resources :users, except: [:new, :create, :destroy]

  resources :paths do
    resources :comments
    resources :votes
    resources :steps, except: [:show]
  end

  resources :assets, except: [:new] do
    resources :comments
    resources :votes
  end

  resources :tags, only: [:create, :new]
end

app/models/asset.rb
class Asset < ActiveRecord::Base
  default_scope { order(:created_at => :desc) }

  belongs_to :user
  has_and_belongs_to_many :tags
  has_many :steps
  has_many :comments, as: :commentable
  has_many :votes, as: :voteable

  validates :title, :description, :url, :user_id, presence: true
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  include ApplicationHelper
  before_action :redirect_to_sign_up
  before_action :check_owner, only: [:edit, :update, :destroy]

  def index
    @assets = Asset.where(user_id: current_user.id)
  end

  def show
    @asset = Asset.find(params[:id])
    @votes_count = vote_count(params[:id], 'Asset')
  end

  def create
    asset = Asset.new(asset_params.merge(user_id: current_user.id))
    if asset.save
      render json: asset
    else
      render :new
    end
  end

  def edit
    @asset = Asset.find(params[:id])
  end

  def update
    asset = Asset.find(params[:id])
    asset.update_attributes(asset_params)

    if asset.save
      redirect_to asset_path(asset)
    else
      render :edit
    end
  end

  def destroy
    asset = Asset.find(params[:id]).destroy
    redirect_to assets_path
  end

  private
  def asset_params
    params.require(:asset).permit(:title, :description, :url, :category)
  end

  def check_owner
    unless Asset.find(params[:id]).user_id == current_user.id
      flash[:alert] = "You cannot edit or destroy an asset you do not own!"
      redirect_to paths_path and return
    end
  end
end

app/views/assets/_new.html.erb
<div class="login">
  <h2 class="path-header">New Link</h2>
  <%= form_for :asset, class: 'new-asset', url: '/assets' do |f| %>
    <%= f.label :title %><br />
    <div><%= f.text_field :title, :class =>"title-field" %></div>
    <%= f.label :description%><br />
    <div><%= f.text_area :description, :class =>"title-field" %></div>
    <%= f.label :url %><br />
    <div><%= f.url_field :url, :class =>"title-field"%></div>
    <%= f.label :category %>
    <div><%= f.select :category, options_for_select([['Book', 'book'], ['Video', 'video'], ['Audio', 'audio'], ['Tutorial', 'tutorial'], ['Practice', 'practice'], ['Event', 'event'], ['Other', 'other']]) %></div>
    <%= f.submit "Save Link", :class => "styled-button" %>
  <% end %>
</div>

app/views/assets/edit.html.erb
<div class="login">
  <h2 class="path-header">Edit Link</h2>
  <%= form_for @asset, class: 'edit-asset' do |f| %>
    <%= f.label :title %><br />
    <div><%= f.text_field :title %></div>
    <%= f.label :description %><br />
    <div><%= f.text_area :description, :class =>"description-field" %></div>
    <%= f.label :url %><br />
    <div><%= f.url_field :url, :class =>"description-field" %></div>
    <%= f.submit :class=>"styled-button" %>
  <% end %>
</div>

app/views/assets/index.html.erb
<div class="login">
  <button class="styled-button create-assets-button">Create Asset</button>
  <div id="assets-partial">
      <%= render 'assets/new', layout: false, locals: {asset: @new_asset} %>
  </div>
  <% if @assets.empty? %>
    <h3>There are currently no assets to display!</h3>
  <% else %>
    <div id="asset-list">
      <% @assets.each do |asset| %>
        <div class="asset">
          <h3><%= asset.title %></h3>
            <button class="styled-button"><%= link_to "Details", asset_path(asset) %></button>
            <button class="styled-button"><a href="<%= asset.url %>">View Asset</a></button>
          <p>Description: <%= asset.description %></p>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/assets/show.html.erb
<div class="login">
  <h1 class="path-header"><%= @asset.title %></h1>
  <p class="asset-description"><%= @asset.description %></p>
  <p class="asset-link"><%= link_to @asset.url, @asset.url %></p>
  <% if check_user_id(@asset) %>
    <button class="styled-button"><%= link_to "Edit", edit_asset_path(@asset) %></button>
    <button class="styled-button"><%= link_to "Delete", asset_path(@asset), :method => :delete %></button>
  <% end %>
  <p>Votes: <span id="vote-count"><%= @votes_count %></span></p>
  <% if user_signed_in? %>
    <button class="vote styled-button" data-vote-state=true data-voteable-id=<%= @asset.id %> data-voteable-type="Asset" >Upvote!</button>
    <button class="vote styled-button" data-vote-state=false data-voteable-id=<%= @asset.id %> data-voteable-type="Asset" >Downvote!</button>
  <% end %>
  <h3>Comments:</h3>
    <% if user_signed_in? %>
    <button class="styled-button" id="new-comment-button"><%= link_to "New Comment", polymorphic_path([@asset, Comment]) %></button>
   <% end %>
  <% @asset.comments.each do |comment|%>
    <p><%= comment.created_at.strftime('%a %d %b %Y %I:%M %p') %> By: <%= comment.user.first_name %></p>
    <p><%= link_to comment.body, polymorphic_path([@asset, comment]) %><br>
  <% end %>
</div>